services:
  ipfs:
    image: ipfs/kubo:v0.38.2
    restart: unless-stopped
    environment:
      IPFS_PROFILE: server
      IPFS_PATH: /data/ipfs
      IPFS_SWARM_KEY_FILE: /run/secrets/swarm.key
    entrypoint: ["/bin/sh", "/init-private-swarm.sh"]
    expose:
      - "5001"
      - "8080"
      - "4001"
    volumes:
      - ipfs-data:/data/ipfs
      - ./bootstrap-peers.txt:/bootstrap-peers.txt:ro
      - ./init-private-swarm.sh:/init-private-swarm.sh:ro
    secrets:
      - swarm.key
    networks:
      - ipfs-backend

volumes:
  ipfs-data:

secrets:
  swarm.key:
    file: ./swarm.key

networks:
  ipfs-backend:
    internal: true
