<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CanDoItAll.Processes.Contracts\CanDoItAll.Processes.Contracts.csproj" />
    <ProjectReference Include="..\CanDoItAll.Processes.Abstractions\CanDoItAll.Processes.Abstractions.csproj" />
    <ProjectReference Include="..\CanDoItAll.Processes.Core\CanDoItAll.Processes.Core.csproj" />
    <ProjectReference Include="..\CanDoItAll.Processes.Templates\CanDoItAll.Processes.Templates.csproj" />
    <ProjectReference Include="..\Drivers\CanDoItAll.Processes.Drivers.Abstractions\CanDoItAll.Processes.Drivers.Abstractions.csproj" />
  </ItemGroup>

</Project>
