<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <CopyRepositoryTemplatesToOutput>false</CopyRepositoryTemplatesToOutput>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../Modules/CanDoItAll.Modules.Workspace.StorageSelection.Contracts/CanDoItAll.Modules.Workspace.StorageSelection.Contracts.csproj" />
    <ProjectReference Include="../CanDoItAll.AppComponents/CanDoItAll.AppComponents.csproj" />
  </ItemGroup>
</Project>
