<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <CopyRepositoryTemplatesToOutput>false</CopyRepositoryTemplatesToOutput>
  </PropertyGroup>
  <ItemGroup>
    <SupportedPlatform Include="browser" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="$(MicrosoftAspNetCoreComponentsVersion)" />
    <PackageReference Include="CanDoItAll.Components.BaseLib" Version="$(CanDoItAllComponentsPackageVersion)" />
    <ProjectReference Include="../../MAF/Common/CanDoItAll.AgentFramework.Models/CanDoItAll.AgentFramework.Models.csproj" />
    <ProjectReference Include="../CanDoItAll.Conversations.Components/CanDoItAll.Conversations.Components.csproj" />
  </ItemGroup>
</Project>
