namespace CanDoItAll.Modules.AgentFramework.Hosting;

internal sealed partial class ScenarioHarnessAgentRuntime
{
    private const string CalculatorSpecMarkdown =
        """
        # Calculator Specification

        Build a simple four-operation calculator in the default Blazor home page.

        Requirements:
        - Two numeric inputs.
        - Buttons for add, subtract, multiply, and divide.
        - Clear error handling for divide by zero.
        - Small explanatory README with build and run instructions.
        """;

    private const string CalculatorReadme =
        """
        # Scenario Calculator

        This Blazor Web App was generated by the integrated AgentFramework scenario harness.

        ## Run

        ```powershell
        dotnet run --project ScenarioCalculator.csproj
        ```

        ## What it does

        The home page was replaced with a simple calculator that supports addition, subtraction, multiplication, and division.
        """;

    private const string CalculatorHomeRazor =
        """
        @page "/"

        <PageTitle>Scenario Calculator</PageTitle>

        <div class="container py-4">
            <h1>Scenario Calculator</h1>
            <p>Enter two numbers, choose an operation, and review the result.</p>

            <div class="row g-3 mt-2">
                <div class="col-md-6">
                    <label class="form-label">First number</label>
                    <InputNumber @bind-Value="firstNumber" class="form-control" />
                </div>
                <div class="col-md-6">
                    <label class="form-label">Second number</label>
                    <InputNumber @bind-Value="secondNumber" class="form-control" />
                </div>
            </div>

            <div class="d-flex flex-wrap gap-2 mt-4">
                <button class="btn btn-primary" @onclick="Add">Add</button>
                <button class="btn btn-secondary" @onclick="Subtract">Subtract</button>
                <button class="btn btn-success" @onclick="Multiply">Multiply</button>
                <button class="btn btn-warning" @onclick="Divide">Divide</button>
            </div>

            <div class="mt-4">
                <h2>Result</h2>
                <p>@resultMessage</p>
            </div>
        </div>

        @code {
            private decimal firstNumber;
            private decimal secondNumber;
            private string resultMessage = "Choose an operation to calculate the result.";

            private void Add()
            {
                resultMessage = $"{firstNumber} + {secondNumber} = {firstNumber + secondNumber}";
            }

            private void Subtract()
            {
                resultMessage = $"{firstNumber} - {secondNumber} = {firstNumber - secondNumber}";
            }

            private void Multiply()
            {
                resultMessage = $"{firstNumber} × {secondNumber} = {firstNumber * secondNumber}";
            }

            private void Divide()
            {
                if (secondNumber == 0)
                {
                    resultMessage = "Division by zero is not allowed.";
                    return;
                }

                resultMessage = $"{firstNumber} ÷ {secondNumber} = {decimal.Round(firstNumber / secondNumber, 4)}";
            }
        }
        """;

    private const string ApprovalTaskMarkdown =
        """
        # Approval Task

        Resume the guarded mutation only after explicit approval.
        """;

    private const string ApprovalProofMarkdown =
        """
        # Approval Proof

        The scenario harness resumed after a persisted approval decision and created this artifact through the guarded path.
        """;

    private const string ApprovalInventoryPowerShellScript =
        """
        param(
            [Parameter(Mandatory = $true)]
            [string]$TargetPath
        )

        Get-ChildItem -Path $TargetPath -Recurse -Force |
            Select-Object FullName, Length, LastWriteTimeUtc |
            ConvertTo-Json -Depth 4
        """;
}
