<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>CanDoItAll.Mcp.Components</AssemblyName>
    <RootNamespace>CanDoItAll.Mcp.Components</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="ModelContextProtocol" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CanDoItAll.Components.BaseLib" Version="0.1.0" />
    <PackageReference Include="CanDoItAll.Components.CanvasLib" Version="0.1.0" />
    <PackageReference Include="CanDoItAll.Components.Charts" Version="0.1.0" />
    <PackageReference Include="CanDoItAll.Components.Common" Version="0.1.0" />
    <PackageReference Include="CanDoItAll.Components.Mermaid" Version="0.1.0" />
    <PackageReference Include="CanDoItAll.Components.Sandbox" Version="0.1.0" />
    <ProjectReference Include="..\CanDoItAll.Mcp.Core\CanDoItAll.Mcp.Core.csproj" />
  </ItemGroup>

</Project>
