<Project>
  <ItemGroup>
    <ProcessTemplatePackContent Include="$(MSBuildThisFileDirectory)output\process-template-pack\**\*.*" />
  </ItemGroup>

  <Target Name="CopyProcessTemplatePack" AfterTargets="Build">
    <MakeDir Directories="$(TargetDir)output\process-template-pack" />
    <Copy
      SourceFiles="@(ProcessTemplatePackContent)"
      DestinationFiles="@(ProcessTemplatePackContent->'$(TargetDir)output\process-template-pack\%(RecursiveDir)%(Filename)%(Extension)')"
      SkipUnchangedFiles="true" />
  </Target>
</Project>
