<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <NuGetAudit>false</NuGetAudit>
    <AssemblyName>StartupDispatchCapture</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <Reference Include="Microsoft.Diagnostics.NETCore.Client">
      <HintPath>C:\Users\lucys\.nuget\packages\microsoft.diagnostics.netcore.client\0.2.510501\lib\net6.0\Microsoft.Diagnostics.NETCore.Client.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Microsoft.Diagnostics.Tracing.TraceEvent">
      <HintPath>C:\Users\lucys\.nuget\packages\microsoft.diagnostics.tracing.traceevent\3.1.21\lib\netstandard2.0\Microsoft.Diagnostics.Tracing.TraceEvent.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Microsoft.Diagnostics.FastSerialization">
      <HintPath>C:\Users\lucys\.nuget\packages\microsoft.diagnostics.tracing.traceevent\3.1.21\lib\netstandard2.0\Microsoft.Diagnostics.FastSerialization.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
