namespace CanDoItAll.Components.BaseLib;

internal static class FontAwesomeIconCatalog
{
    private static readonly IReadOnlyDictionary<string, string> MaterialToFontAwesome = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["account_balance_wallet"] = "fa-solid fa-wallet",
        ["account_circle"] = "fa-solid fa-circle-user",
        ["add"] = "fa-solid fa-plus",
        ["add_card"] = "fa-solid fa-credit-card",
        ["add_circle"] = "fa-solid fa-circle-plus",
        ["admin_panel_settings"] = "fa-solid fa-user-shield",
        ["ai"] = "fa-solid fa-robot",
        ["album"] = "fa-solid fa-compact-disc",
        ["audio"] = "fa-solid fa-wave-square",
        ["archive"] = "fa-solid fa-box-archive",
        ["arch"] = "fa-solid fa-compass-drafting",
        ["arrow_back"] = "fa-solid fa-arrow-left",
        ["arrow_forward"] = "fa-solid fa-arrow-right",
        ["article"] = "fa-solid fa-file-lines",
        ["asset"] = "fa-solid fa-folder-open",
        ["assure"] = "fa-solid fa-clipboard-check",
        ["audit"] = "fa-solid fa-clipboard-check",
        ["auto_awesome"] = "fa-solid fa-wand-magic-sparkles",
        ["backlog"] = "fa-solid fa-inbox",
        ["bolt"] = "fa-solid fa-bolt",
        ["block"] = "fa-solid fa-cubes-stacked",
        ["bookmark_add"] = "fa-solid fa-bookmark",
        ["build"] = "fa-solid fa-hammer",
        ["cancel"] = "fa-solid fa-ban",
        ["center_focus_strong"] = "fa-solid fa-bullseye",
        ["check"] = "fa-solid fa-check",
        ["check_circle"] = "fa-solid fa-circle-check",
        ["cleaning_services"] = "fa-solid fa-broom",
        ["clear"] = "fa-solid fa-eraser",
        ["choice"] = "fa-solid fa-gavel",
        ["close"] = "fa-solid fa-xmark",
        ["cloud_download"] = "fa-solid fa-cloud-arrow-down",
        ["cloud_sync"] = "fa-solid fa-cloud-arrow-up",
        ["console"] = "fa-solid fa-terminal",
        ["content_copy"] = "fa-solid fa-copy",
        ["crop_square"] = "fa-regular fa-square",
        ["dashboard"] = "fa-solid fa-gauge-high",
        ["database"] = "fa-solid fa-database",
        ["date"] = "fa-solid fa-calendar-days",
        ["delete"] = "fa-solid fa-trash",
        ["delete_forever"] = "fa-solid fa-trash-can",
        ["delete_sweep"] = "fa-solid fa-broom",
        ["deliver"] = "fa-solid fa-truck",
        ["description"] = "fa-solid fa-file-lines",
        ["developer_mode"] = "fa-solid fa-code",
        ["dns"] = "fa-solid fa-network-wired",
        ["docker"] = "fa-brands fa-docker",
        ["docx"] = "fa-solid fa-file-word",
        ["domain"] = "fa-solid fa-globe",
        ["dotnet"] = "fa-solid fa-code",
        ["download"] = "fa-solid fa-download",
        ["draw"] = "fa-solid fa-pen",
        ["evidence"] = "fa-solid fa-camera",
        ["excel"] = "fa-solid fa-file-excel",
        ["expand"] = "fa-solid fa-up-right-and-down-left-from-center",
        ["expand_less"] = "fa-solid fa-chevron-up",
        ["expand_more"] = "fa-solid fa-chevron-down",
        ["favorite"] = "fa-solid fa-heart",
        ["feature"] = "fa-solid fa-star",
        ["feedback"] = "fa-solid fa-comments",
        ["file"] = "fa-solid fa-file",
        ["first_page"] = "fa-solid fa-backward-fast",
        ["flow"] = "fa-solid fa-diagram-project",
        ["folder"] = "fa-solid fa-folder",
        ["fork"] = "fa-solid fa-code-fork",
        ["freelancer"] = "fa-solid fa-user-pen",
        ["frame"] = "fa-regular fa-square",
        ["gavel"] = "fa-solid fa-gavel",
        ["graphic_eq"] = "fa-solid fa-sliders",
        ["groups"] = "fa-solid fa-users",
        ["hearing"] = "fa-solid fa-headphones",
        ["hearing_disabled"] = "fa-solid fa-volume-xmark",
        ["help"] = "fa-solid fa-circle-question",
        ["help_outline"] = "fa-regular fa-circle-question",
        ["home"] = "fa-solid fa-house",
        ["image"] = "fa-solid fa-image",
        ["info"] = "fa-solid fa-circle-info",
        ["infra"] = "fa-solid fa-server",
        ["inventory_2"] = "fa-solid fa-box-open",
        ["issue"] = "fa-solid fa-bug",
        ["json"] = "fa-solid fa-file-code",
        ["key"] = "fa-solid fa-key",
        ["library_music"] = "fa-solid fa-book-open",
        ["link"] = "fa-solid fa-link",
        ["link_off"] = "fa-solid fa-link-slash",
        ["login"] = "fa-solid fa-right-to-bracket",
        ["logout"] = "fa-solid fa-right-from-bracket",
        ["looks_3"] = "fa-solid fa-list-ol",
        ["looks_one"] = "fa-solid fa-list-ol",
        ["looks_two"] = "fa-solid fa-list-ol",
        ["location"] = "fa-solid fa-location-dot",
        ["log"] = "fa-solid fa-file-lines",
        ["manage_accounts"] = "fa-solid fa-users-gear",
        ["markdown"] = "fa-brands fa-markdown",
        ["market"] = "fa-solid fa-bullhorn",
        ["menu"] = "fa-solid fa-bars",
        ["meeting"] = "fa-solid fa-calendar-check",
        ["mermaid"] = "fa-solid fa-diagram-project",
        ["migration"] = "fa-solid fa-shuffle",
        ["minimize"] = "fa-solid fa-window-minimize",
        ["monitor_heart"] = "fa-solid fa-heart-pulse",
        ["money"] = "fa-solid fa-sack-dollar",
        ["music_note"] = "fa-solid fa-music",
        ["network_ping"] = "fa-solid fa-signal",
        ["note"] = "fa-solid fa-note-sticky",
        ["note_add"] = "fa-solid fa-note-sticky",
        ["open"] = "fa-solid fa-arrow-up-right-from-square",
        ["open_in_new"] = "fa-solid fa-up-right-from-square",
        ["ops"] = "fa-solid fa-gears",
        ["org"] = "fa-solid fa-sitemap",
        ["paid"] = "fa-solid fa-money-check-dollar",
        ["partner"] = "fa-solid fa-handshake",
        ["pause"] = "fa-solid fa-pause",
        ["payment"] = "fa-solid fa-money-check-dollar",
        ["payments"] = "fa-solid fa-money-bill-wave",
        ["pdf"] = "fa-solid fa-file-pdf",
        ["people"] = "fa-solid fa-users",
        ["person"] = "fa-solid fa-user",
        ["person_add"] = "fa-solid fa-user-plus",
        ["phase"] = "fa-solid fa-layer-group",
        ["piano"] = "fa-solid fa-keyboard",
        ["picture_as_pdf"] = "fa-solid fa-file-pdf",
        ["play_arrow"] = "fa-solid fa-play",
        ["play_circle"] = "fa-solid fa-circle-play",
        ["plan"] = "fa-solid fa-calendar-days",
        ["playlist_add_check"] = "fa-solid fa-list-check",
        ["playlist_play"] = "fa-solid fa-play",
        ["playlist_remove"] = "fa-solid fa-list",
        ["plug"] = "fa-solid fa-plug",
        ["power"] = "fa-solid fa-power-off",
        ["powershell"] = "fa-solid fa-terminal",
        ["progress"] = "fa-solid fa-chart-line",
        ["progress-0"] = "fa-regular fa-circle",
        ["progress-100"] = "fa-solid fa-circle-check",
        ["progress-started"] = "fa-solid fa-play",
        ["prompt"] = "fa-solid fa-wand-magic-sparkles",
        ["publish"] = "fa-solid fa-upload",
        ["published_with_changes"] = "fa-solid fa-list-check",
        ["qa"] = "fa-solid fa-clipboard-check",
        ["query_stats"] = "fa-solid fa-chart-line",
        ["radar"] = "fa-solid fa-satellite-dish",
        ["recording"] = "fa-solid fa-microphone-lines",
        ["refresh"] = "fa-solid fa-rotate",
        ["release"] = "fa-solid fa-rocket",
        ["relink"] = "fa-solid fa-arrows-rotate",
        ["remove"] = "fa-solid fa-minus",
        ["repo"] = "fa-solid fa-code-branch",
        ["research"] = "fa-solid fa-magnifying-glass",
        ["replay"] = "fa-solid fa-rotate-left",
        ["rev"] = "fa-solid fa-rotate",
        ["revision"] = "fa-solid fa-rotate",
        ["risk"] = "fa-solid fa-triangle-exclamation",
        ["restart_alt"] = "fa-solid fa-rotate-left",
        ["restore"] = "fa-solid fa-rotate-left",
        ["rocket_launch"] = "fa-solid fa-rocket",
        ["runtime"] = "fa-solid fa-terminal",
        ["save"] = "fa-solid fa-floppy-disk",
        ["school"] = "fa-solid fa-graduation-cap",
        ["screenshot"] = "fa-solid fa-camera",
        ["search"] = "fa-solid fa-magnifying-glass",
        ["section"] = "fa-solid fa-table-cells-large",
        ["sell"] = "fa-solid fa-tags",
        ["send"] = "fa-solid fa-paper-plane",
        ["sensors"] = "fa-solid fa-satellite-dish",
        ["server"] = "fa-solid fa-server",
        ["session"] = "fa-solid fa-window-restore",
        ["settings"] = "fa-solid fa-gear",
        ["shield"] = "fa-solid fa-shield-halved",
        ["ship"] = "fa-solid fa-truck-fast",
        ["shopping_cart"] = "fa-solid fa-cart-shopping",
        ["skip"] = "fa-solid fa-forward-step",
        ["skip_next"] = "fa-solid fa-forward-step",
        ["skip_previous"] = "fa-solid fa-backward-step",
        ["speed"] = "fa-solid fa-gauge",
        ["step"] = "fa-solid fa-list-ol",
        ["star"] = "fa-solid fa-star",
        ["stop"] = "fa-solid fa-stop",
        ["store"] = "fa-solid fa-store",
        ["subdirectory_arrow_left"] = "fa-solid fa-reply",
        ["summary"] = "fa-solid fa-chart-pie",
        ["support"] = "fa-solid fa-life-ring",
        ["sync"] = "fa-solid fa-arrows-rotate",
        ["tailwind"] = "fa-solid fa-wind",
        ["task_alt"] = "fa-solid fa-circle-check",
        ["task"] = "fa-solid fa-list-check",
        ["test"] = "fa-solid fa-vial",
        ["text"] = "fa-solid fa-file-lines",
        ["token"] = "fa-solid fa-coins",
        ["touch_app"] = "fa-solid fa-hand-pointer",
        ["track_changes"] = "fa-solid fa-bullseye",
        ["transcript"] = "fa-solid fa-closed-captioning",
        ["tune"] = "fa-solid fa-sliders",
        ["unfold_more"] = "fa-solid fa-up-down",
        ["unlink"] = "fa-solid fa-link-slash",
        ["upload"] = "fa-solid fa-upload",
        ["upload_file"] = "fa-solid fa-file-arrow-up",
        ["use"] = "fa-solid fa-check-double",
        ["usb"] = "fa-brands fa-usb",
        ["visibility"] = "fa-solid fa-eye",
        ["visibility_off"] = "fa-solid fa-eye-slash",
        ["video"] = "fa-solid fa-video",
        ["volume_up"] = "fa-solid fa-volume-high",
        ["watch"] = "fa-solid fa-eye",
        ["workspace_premium"] = "fa-solid fa-crown"
    };

    public static bool TryResolveCssClass(string? iconToken, out string cssClass)
    {
        cssClass = string.Empty;
        if (string.IsNullOrWhiteSpace(iconToken))
        {
            return false;
        }

        var normalizedToken = iconToken.Trim();
        if (IsFontAwesomeClassList(normalizedToken))
        {
            cssClass = normalizedToken;
            return true;
        }

        if (MaterialToFontAwesome.TryGetValue(normalizedToken, out var mappedCssClass))
        {
            cssClass = mappedCssClass;
            return true;
        }

        return false;
    }

    private static bool IsFontAwesomeClassList(string iconToken)
    {
        return iconToken.Contains("fa-", StringComparison.OrdinalIgnoreCase);
    }
}


