namespace CanDoItAll.Modules.AgentFramework.Hosting;

internal sealed partial class ScenarioHarnessAgentRuntime
{
    private const string GeneratedBlazorAppSpecMarkdown =
        """
        # Generated Blazor App Specification

        Build a small interactive work-item surface in the default Blazor home page.

        Requirements:
        - One text input for a new work item.
        - An action that adds the item to an in-memory list.
        - An action that marks the first open item as done.
        - Visible counts for open and completed items.
        - Small explanatory README with build and run instructions.
        """;

    private const string GeneratedBlazorAppReadme =
        """
        # Generated Blazor App

        This Blazor Web App was generated by the integrated AgentFramework scenario harness.

        ## Run

        ```powershell
        dotnet run --project GeneratedBlazorApp.csproj
        ```

        ## What it does

        The home page was replaced with a compact work board that adds items, marks one item done, and displays live counts.
        """;

    private const string GeneratedBlazorAppDirectoryBuildTargets =
        """
        <Project>
          <PropertyGroup>
            <CopyRepositoryTemplatesToOutput>false</CopyRepositoryTemplatesToOutput>
          </PropertyGroup>
        </Project>
        """;

    private const string GeneratedBlazorAppHomeRazor =
        """
        @page "/"

        <PageTitle>Generated Blazor App</PageTitle>

        <div class="container py-4">
            <h1>Generated Blazor App</h1>
            <p>Add work items, mark progress, and review the current queue.</p>

            <div class="row g-3 mt-2">
                <div class="col-md-8">
                    <label class="form-label">Work item</label>
                    <InputText @bind-Value="newNote" class="form-control" />
                </div>
                <div class="col-md-4 d-flex align-items-end gap-2">
                    <button class="btn btn-primary" @onclick="AddNote">Add item</button>
                    <button class="btn btn-secondary" @onclick="MarkFirstDone" disabled="@(!items.Any(item => !item.IsDone))">Mark first done</button>
                </div>
            </div>

            <div class="d-flex flex-wrap gap-3 mt-4">
                <span class="badge text-bg-info">Open: @items.Count(item => !item.IsDone)</span>
                <span class="badge text-bg-success">Done: @items.Count(item => item.IsDone)</span>
            </div>

            <ul class="list-group mt-4">
                @foreach (var item in items)
                {
                    <li class="list-group-item d-flex justify-content-between">
                        <span>@item.Text</span>
                        <span>@(item.IsDone ? "Done" : "Open")</span>
                    </li>
                }
            </ul>

            @if (!string.IsNullOrWhiteSpace(message))
            {
                <p class="mt-3">@message</p>
            }
        </div>

        @code {
            private readonly List<PlanningItem> items = [];
            private string newNote = string.Empty;
            private string message = "No notes yet.";

            private void AddNote()
            {
                if (string.IsNullOrWhiteSpace(newNote))
                {
                    message = "Enter an item before adding it.";
                    return;
                }

                items.Add(new PlanningItem(newNote.Trim()));
                newNote = string.Empty;
                message = "Item added.";
            }

            private void MarkFirstDone()
            {
                var item = items.FirstOrDefault(item => !item.IsDone);
                if (item is null)
                {
                    message = "No open notes to mark done.";
                    return;
                }

                item.IsDone = true;
                message = "First open note marked done.";
            }

            private sealed class PlanningItem(string text)
            {
                public string Text { get; } = text;
                public bool IsDone { get; set; }
            }
        }
        """;

    private const string ApprovalTaskMarkdown =
        """
        # Approval Task

        Resume the guarded mutation only after explicit approval.
        """;

    private const string ApprovalProofMarkdown =
        """
        # Approval Proof

        The scenario harness resumed after a persisted approval decision and created this artifact through the guarded path.
        """;

    private const string ApprovalInventoryPowerShellScript =
        """
        param(
            [Parameter(Mandatory = $true)]
            [string]$TargetPath
        )

        Get-ChildItem -Path $TargetPath -Recurse -Force |
            Select-Object FullName, Length, LastWriteTimeUtc |
            ConvertTo-Json -Depth 4
        """;
}
