<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CanDoItAll.AgentFramework.Models\CanDoItAll.AgentFramework.Models.csproj" />
    <ProjectReference Include="..\CanDoItAll.AgentFramework.Core\CanDoItAll.AgentFramework.Core.csproj" />
    <ProjectReference Include="..\CanDoItAll.Tools.Documents\CanDoItAll.Tools.Documents.csproj" />
    <ProjectReference Include="..\CanDoItAll.Modules.Processes\CanDoItAll.Modules.Processes.csproj" />
    <ProjectReference Include="..\CanDoItAll.Modules.Projects\CanDoItAll.Modules.Projects.csproj" />
    <ProjectReference Include="..\CanDoItAll.Modules.Workbench\CanDoItAll.Modules.Workbench.csproj" />
    <ProjectReference Include="..\CanDoItAll.Modules.Workspace\CanDoItAll.Modules.Workspace.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="2.9.0-beta.1" />
    <PackageReference Include="ExcelDataReader" Version="3.8.0" />
    <PackageReference Include="Microsoft.Agents.AI" Version="1.3.0" />
    <PackageReference Include="Microsoft.Agents.AI.A2A" Version="1.3.0-preview.260423.1" />
    <PackageReference Include="Microsoft.Agents.AI.Mem0" Version="1.0.0-preview.251028.1" />
    <PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.3.0" />
    <PackageReference Include="Microsoft.Agents.AI.Workflows" Version="1.3.0" />
    <PackageReference Include="ModelContextProtocol" Version="1.1.0" />
    <PackageReference Include="OllamaSharp" Version="5.4.25" />
    <PackageReference Include="OpenTelemetry.Api" Version="1.15.3" />
    <PackageReference Include="PdfPig" Version="0.1.14" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);OPENAI001;MEAI001;MAAI001</NoWarn>
  </PropertyGroup>

</Project>
