using System.Text.Json.Serialization;
using CanDoItAll.AgentFramework.Llm.Abstractions;
using CanDoItAll.AgentFramework.Models;
using CanDoItAll.AgentFramework.Llm.SimpleChats.Operations;

namespace CanDoItAll.Web.Api;

/// <summary>
/// Body of <c>POST /api/llm-conversations/{conversationId}/turns</c>: one user message with the preconditions of the
/// turn. Resending an <c>operationId</c> is a replay only when the conversation, <c>expectedTranscriptRevision</c> and
/// <c>message</c> are identical; otherwise it is rejected. Members not listed here are rejected.
/// </summary>
/// <param name="OperationId">
/// A new GUID generated by the client for this turn. It becomes the operation identifier and the turn identifier and is
/// the idempotency key: resend the same value with an identical body to retry an ambiguous request, and use a new value
/// for every new turn. The empty GUID is rejected.
/// </param>
/// <param name="ExpectedTranscriptRevision">
/// The conversation's current <c>transcriptRevision</c>, from <c>GET /api/llm-conversations/{conversationId}</c> or the
/// previous successful turn's <c>resultingTranscriptRevision</c>. Not negative; a stale value is rejected with 409
/// <c>llm-chat.transcript-revision-conflict</c>.
/// </param>
/// <param name="Message">
/// The user message, stored in the transcript exactly as sent. Not blank; at most 400,000 characters (UTF-16 code
/// units).
/// </param>
[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
internal sealed record SendLlmChatTurnApiRequest(
    Guid OperationId,
    long ExpectedTranscriptRevision,
    string Message);

/// <summary>
/// An LLM Chat turn operation: the durable, asynchronous execution of one turn created by
/// <c>POST /api/llm-conversations/{conversationId}/turns</c>. It carries the operation status, the committed assistant
/// reply once there is one, the recorded failure, links for following the operation and up to 100 provider invocation
/// attempts. Returned by the turn, operation read, cancel, reconcile and abandon operations.
/// </summary>
/// <param name="Schema">Contract identifier of this object, always <c>candoitall.llm-chat-operation.v1</c>.</param>
/// <param name="OperationId">
/// Identifier of the operation: the client-supplied <c>operationId</c> of the turn, which is also the turn identifier.
/// </param>
/// <param name="ConversationId">Identifier of the conversation the turn belongs to.</param>
/// <param name="Status">
/// Current status as a camel-case string: <c>pending</c> (admitted, waiting for a dispatcher), <c>running</c> (being
/// executed), <c>cancellationRequested</c>, <c>succeeded</c>, <c>failed</c>, <c>cancelled</c> or
/// <c>recoveryRequired</c> (interrupted with an unknown outcome). <c>succeeded</c>, <c>failed</c> and <c>cancelled</c>
/// are final; <c>recoveryRequired</c> needs reconciliation or abandonment.
/// </param>
/// <param name="Replayed">
/// True only in a turn response that returned an existing operation for a repeated identical request instead of
/// admitting a new turn; false in all other responses.
/// </param>
/// <param name="ExpectedTranscriptRevision">Transcript revision the turn was admitted against, as sent with it.</param>
/// <param name="ResultingTranscriptRevision">
/// Transcript revision after the assistant reply was committed; null unless the operation succeeded. Use it as the next
/// turn's <c>expectedTranscriptRevision</c>.
/// </param>
/// <param name="LastEventSequence">
/// Sequence number of the operation's latest event when this snapshot was read. Open the event stream with
/// <c>after</c> set to this value to receive only later events.
/// </param>
/// <param name="StatusUrl">Relative URL of this operation, <c>/api/llm-chat-operations/{operationId}</c>.</param>
/// <param name="EventsUrl">Relative URL of the operation's server-sent event stream.</param>
/// <param name="CancelUrl">Relative URL for requesting cancellation with <c>POST</c>.</param>
/// <param name="InvocationAttempts">
/// Provider invocation attempts in ascending <c>ordinal</c> order; at most 100, empty before the first attempt starts.
/// </param>
/// <param name="AssistantMessage">
/// The assistant reply this turn committed to the transcript; null until one is committed.
/// </param>
/// <param name="Failure">
/// The recorded failure: present when the operation failed, was cancelled or requires recovery; null otherwise.
/// </param>
/// <param name="StartedAtUtc">Instant the turn was admitted, in UTC.</param>
/// <param name="CompletedAtUtc">
/// Instant the operation became <c>succeeded</c>, <c>failed</c> or <c>cancelled</c>, in UTC; null before that,
/// including while it requires recovery.
/// </param>
internal sealed record LlmChatOperationApiResponse(
    string Schema,
    Guid OperationId,
    Guid ConversationId,
    LlmChatOperationStatus Status,
    bool Replayed,
    long ExpectedTranscriptRevision,
    long? ResultingTranscriptRevision,
    long LastEventSequence,
    string StatusUrl,
    string EventsUrl,
    string CancelUrl,
    IReadOnlyList<LlmChatInvocationAttemptApiResponse> InvocationAttempts,
    LlmChatMessageApiResponse? AssistantMessage,
    LlmChatOperationFailureApiResponse? Failure,
    DateTimeOffset StartedAtUtc,
    DateTimeOffset? CompletedAtUtc);

/// <summary>A failure recorded for an LLM Chat operation or for one of its provider invocation attempts.</summary>
/// <param name="Code">
/// Stable failure code starting with <c>llm-chat.</c>, for example <c>llm-chat.provider-unavailable</c>,
/// <c>llm-chat.deadline-exceeded</c>, <c>llm-chat.cancelled</c> or <c>llm-chat.operation-recovery-required</c>. Branch
/// on this code.
/// </param>
/// <param name="Retryable">
/// True when the cause is transient (provider or dispatcher unavailable, deadline exceeded, database profile changed,
/// concurrent storage change), so a new turn with a new <c>operationId</c> can succeed. Resending the same
/// <c>operationId</c> only returns the recorded operation.
/// </param>
internal sealed record LlmChatOperationFailureApiResponse(
    string Code,
    bool Retryable);

/// <summary>
/// Evidence of one provider invocation attempt of an LLM Chat turn: an allowlisted projection that omits the provider
/// profile identity, correlation identifiers and raw provider errors. Unlike the definition resources, this object
/// writes its enum members as JSON integers.
/// </summary>
/// <param name="Ordinal">Position of the attempt within the operation, starting at 1.</param>
/// <param name="ProviderKind">Provider kind as a JSON integer: 0 OpenAi, 1 AzureOpenAi, 2 Ollama, 3 ComfyUi.</param>
/// <param name="Model">Model reported for the attempt.</param>
/// <param name="DeliveryMode">
/// How the reply was obtained, as a JSON integer: 0 Incremental (streamed in parts), 1 CompletedFallback (the provider
/// could not stream, so the reply was obtained in one piece).
/// </param>
/// <param name="FinishReason">
/// Finish reason of a successful attempt as reported by the provider driver, at most 100 characters; null for failed or
/// cancelled attempts.
/// </param>
/// <param name="RequestedThinkingEffort">
/// Thinking effort set by the definition revision, as a JSON integer: 0 None, 6 Minimal, 1 Low, 2 Medium, 3 High,
/// 4 ExtraHigh, 5 Max. Null when the revision leaves it to the provider default.
/// </param>
/// <param name="EffectiveThinkingEffort">
/// Thinking effort applied to the attempt: the requested value or, when none was requested, the provider default for
/// the model, as a JSON integer: 0 None, 6 Minimal, 1 Low, 2 Medium, 3 High, 4 ExtraHigh, 5 Max. Null when neither
/// exists.
/// </param>
/// <param name="Outcome">Result of the attempt, as a JSON integer: 0 Succeeded, 1 Failed, 2 Cancelled.</param>
/// <param name="Usage">Token usage reported for this attempt; zeros when the provider reported none.</param>
/// <param name="Failure">Failure of a failed or cancelled attempt; null for a successful one.</param>
/// <param name="StartedAtUtc">Instant the attempt started, in UTC.</param>
/// <param name="CompletedAtUtc">Instant the attempt ended, in UTC.</param>
internal sealed record LlmChatInvocationAttemptApiResponse(
    int Ordinal,
    ProviderKind ProviderKind,
    string Model,
    LlmStreamingDeliveryMode DeliveryMode,
    string? FinishReason,
    AgentReasoningEffortLevel? RequestedThinkingEffort,
    AgentReasoningEffortLevel? EffectiveThinkingEffort,
    LlmChatInvocationOutcome Outcome,
    LlmChatUsageApiResponse Usage,
    LlmChatOperationFailureApiResponse? Failure,
    DateTimeOffset StartedAtUtc,
    DateTimeOffset CompletedAtUtc);

internal static class LlmChatOperationApiRoutes
{
    public static string Status(Guid operationId)
        => $"/api/llm-chat-operations/{operationId:D}";

    public static string Events(Guid operationId)
        => $"/api/llm-chat-operations/{operationId:D}/events";

    public static string Cancel(Guid operationId)
        => $"/api/llm-chat-operations/{operationId:D}/cancel";

    public static string Reconcile(Guid operationId)
        => $"/api/llm-chat-operations/{operationId:D}/reconcile";
}

internal static class LlmChatOperationApiSchemas
{
    public const string Operation = "candoitall.llm-chat-operation.v1";
}
