using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;

namespace CanDoItAll.Web.Api;

// The generated XML comment transformer finds a schema's description through the CLR type of its JsonTypeInfo. When a
// component schema is first generated from an optional value type, that type is Nullable<T>, which has no
// documentation, so enums and structs used as optional members or query parameters would lose their descriptions.
// This transformer passes the underlying type to the same generated transformer, so the text still comes from the
// type's XML documentation. Only component schemas are filled; a property's own role description is never replaced.
internal sealed class OpenApiNullableTypeDescriptions : IOpenApiSchemaTransformer
{
    private const string GeneratedTransformerName = "XmlCommentSchemaTransformer";
    private const string SchemaIdMetadataKey = "x-schema-id";

    private readonly IOpenApiSchemaTransformer xmlCommentTransformer = CreateGeneratedTransformer();

    public Task TransformAsync(
        OpenApiSchema schema,
        OpenApiSchemaTransformerContext context,
        CancellationToken cancellationToken)
    {
        if (!string.IsNullOrWhiteSpace(schema.Description) ||
            Nullable.GetUnderlyingType(context.JsonTypeInfo.Type) is not { } underlyingType ||
            schema.Metadata is null ||
            !schema.Metadata.TryGetValue(SchemaIdMetadataKey, out var schemaId) ||
            string.IsNullOrEmpty(schemaId as string))
        {
            return Task.CompletedTask;
        }

        var underlyingContext = new OpenApiSchemaTransformerContext
        {
            DocumentName = context.DocumentName,
            JsonTypeInfo = context.JsonTypeInfo.Options.GetTypeInfo(underlyingType),
            JsonPropertyInfo = null,
            ParameterDescription = null,
            ApplicationServices = context.ApplicationServices
        };
        return xmlCommentTransformer.TransformAsync(schema, underlyingContext, cancellationToken);
    }

    private static IOpenApiSchemaTransformer CreateGeneratedTransformer()
    {
        var generatedType = typeof(OpenApiNullableTypeDescriptions).Assembly
            .GetTypes()
            .SingleOrDefault(type =>
                type.Name.EndsWith(GeneratedTransformerName, StringComparison.Ordinal) &&
                typeof(IOpenApiSchemaTransformer).IsAssignableFrom(type))
            ?? throw new InvalidOperationException(
                "The XML comment schema transformer generated by Microsoft.AspNetCore.OpenApi was not found. Enable XML documentation output for the Web project.");
        return (IOpenApiSchemaTransformer)(Activator.CreateInstance(generatedType)
            ?? throw new InvalidOperationException("The generated XML comment schema transformer could not be created."));
    }
}
