<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <AssemblyName>CanDoItAll.Space3D.Mouse.Components</AssemblyName>
    <RootNamespace>CanDoItAll.Space3D.Mouse.Components</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CanDoItAll.Space3D.Mouse.Driver\CanDoItAll.Space3D.Mouse.Driver.csproj" />
    <PackageReference Include="CanDoItAll.Components.BaseLib" Version="0.1.0" />
    <PackageReference Include="CanDoItAll.Components.WebGlLib" Version="0.1.0" />
  </ItemGroup>

</Project>
