<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>CanDoItAll.Space3D.Mouse.Sandbox</AssemblyName>
    <RootNamespace>CanDoItAll.Space3D.Mouse.Sandbox</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CanDoItAll.Space3D.Mouse.Components\CanDoItAll.Space3D.Mouse.Components.csproj" />
    <ProjectReference Include="..\..\CanDoItAll.Components.BaseLib\CanDoItAll.Components.BaseLib.csproj" />
    <ProjectReference Include="..\..\CanDoItAll.Components.WebGlLib\CanDoItAll.Components.WebGlLib.csproj" />
  </ItemGroup>

</Project>
