<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>CanDoItAll.AppComponents</AssemblyName>
    <RootNamespace>CanDoItAll.AppComponents</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.4" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CanDoItAll.Components.BaseLib" Version="0.1.2" />
    <PackageReference Include="CanDoItAll.Components.CanvasLib" Version="0.1.2" />
    <PackageReference Include="CanDoItAll.Components.Common" Version="0.1.2" />
    <PackageReference Include="CanDoItAll.FileTools.FileBrowser.Components" Version="0.2.0" />
    <PackageReference Include="CanDoItAll.FileTools.FileInteraction.Core" Version="0.1.0" />
    <ProjectReference Include="..\..\Foundation\CanDoItAll.SharedKernel\CanDoItAll.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Integration\CanDoItAll.FileTools.Integration.Abstractions\CanDoItAll.FileTools.Integration.Abstractions.csproj" />
  </ItemGroup>

</Project>
