<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <CopyRepositoryTemplatesToOutput>false</CopyRepositoryTemplatesToOutput>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../UI/CanDoItAll.Memory.UI/CanDoItAll.Memory.UI.csproj" />

  </ItemGroup>
</Project>
