<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.4" />
    <PackageReference Include="MQTTnet" Version="5.1.0.1559" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.13.1" />
    <PackageReference Include="Quartz.Serialization.Json" Version="3.13.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CanDoItAll.Components.BaseLib" Version="0.1.0" />
    <ProjectReference Include="..\CanDoItAll.SharedKernel\CanDoItAll.SharedKernel.csproj" />
    <ProjectReference Include="..\CanDoItAll.Infrastructure\CanDoItAll.Infrastructure.csproj" />
    <ProjectReference Include="..\CanDoItAll.Modules.Activity\CanDoItAll.Modules.Activity.csproj" />
    <ProjectReference Include="..\CanDoItAll.Modules.Workspace\CanDoItAll.Modules.Workspace.csproj" />
  </ItemGroup>

</Project>

